#pragma once

#include "shader_builtin_skybox.hlsl.h"
#include "shader_builtin_pbr.hlsl.h"
#include "shader_builtin_pbr_clip.hlsl.h"
#include "shader_builtin_default.hlsl.h"
#include "shader_builtin_blit.hlsl.h"
#include "shader_builtin_unlit.hlsl.h"
#include "shader_builtin_unlit_clip.hlsl.h"
#include "shader_builtin_equirect.hlsl.h"
#include "shader_builtin_blit.hlsl.h"
#include "shader_builtin_font.hlsl.h"
#include "shader_builtin_lines.hlsl.h"
#include "shader_builtin_ui.hlsl.h"
#include "shader_builtin_ui_box.hlsl.h"
#include "shader_builtin_ui_quadrant.hlsl.h"